### ISSUE TITLE
ピン留めが再送信される

### ISSUE THREAD

**Issue by nattyan-tv** [nattyan-tv/tensei_disko#32]
ピン留めが、再送信される条件を満たして**いない**のにも関わらず再送信される。
メッセージは削除されて、ちゃんと送信されてるので、なんか別の...?

**Comment by CrystalAlpha358** [comment]
~~ちょうど62分間隔…？~~

**Comment by nattyan-tv** [comment]
多分Extensionのリロードが出来てなかっただけ
Queue機構で行きます〜

**Comment by nattyan-tv** [comment]
もっかいログ収集からやり直し..(ReReopen...)
