### ISSUE TITLE
pinが行われない

### ISSUE THREAD

**Issue by nattyan-tv** [nattyan-tv/tensei_disko#39]
詳細は追って！！！！！！！！！

**Comment by nattyan-tv** [comment]
`@tasks.loop`のnext_iterationがNoneになってる（けどRunningではある）

**Comment by tasuren** [comment]
これはいつも起きるの？
今も使えない感じ？
再起動しても使えない感じ？

**Comment by nattyan-tv** [comment]
> これはいつも起きるの？

ある時急にぷつりとピン留めが止まる


> 今も使えない感じ？

今は、エラー時に`tasks.loop`の関数を再起動する事で、かろうじて動いてはいる状態(`261-264`)
出来る事なら、早急にエラーの原因をちゃっちゃと特定して修正したい所
(今は「治ってたらいいなー...」みたいな時間)


> 再起動しても使えない感じ？

リロード・再起動すればまた再開する...

**Comment by tasuren** [comment]
エラーで処理が終わった非同期のタスクのエラーは、`task.exception()`で取得できる。
だから、ループが動かなくなった時に、tasksが作ったタスクを`checkPin.get_task()`で取得し、`.exception()`でエラーを取り出して見てみよう。
そしたら、なぜ止まったかがわかるかも。

恐らく、エラー要因は、権限を正しく設定してないチャンネルがどこかにあって、そのチャンネルの処理をしようとして権限エラー(`discord.Forbidden`)が発生し、それによって止まるんだと思う。
